"""empty message

Revision ID: cdfa1f9fa347
Revises: 
Create Date: 2021-10-05 10:59:35.852617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdfa1f9fa347'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('email_address', sa.String(length=225), nullable=False),
    sa.Column('phone_no', sa.String(length=64), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('driver_id')
    )
    op.create_index(op.f('ix_driver_driver_id'), 'driver', ['driver_id'], unique=False)
    op.create_table('good',
    sa.Column('good_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('good_id')
    )
    op.create_table('loader',
    sa.Column('loader_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('email_address', sa.String(length=225), nullable=False),
    sa.Column('phone_no', sa.String(length=64), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('loader_id')
    )
    op.create_index(op.f('ix_loader_loader_id'), 'loader', ['loader_id'], unique=False)
    op.create_table('member',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('email_address', sa.String(length=128), nullable=False),
    sa.Column('phone_no', sa.String(length=32), nullable=False),
    sa.Column('nature_of_produce', sa.String(length=128), nullable=False),
    sa.Column('location_address', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_table('offence',
    sa.Column('offence_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('offence_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vehicle_make',
    sa.Column('make_id', sa.Integer(), nullable=False),
    sa.Column('make_type', sa.String(length=225), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('cost_per_km', sa.Integer(), nullable=True),
    sa.Column('no_of_loaders', sa.Integer(), nullable=True),
    sa.Column('loader_payment', sa.Integer(), nullable=True),
    sa.Column('driver_payment', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('make_id')
    )
    op.create_index(op.f('ix_vehicle_make_make_type'), 'vehicle_make', ['make_type'], unique=True)
    op.create_table('offender',
    sa.Column('offender_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('offence_id', sa.Integer(), nullable=True),
    sa.Column('date_committed', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.driver_id'], ),
    sa.ForeignKeyConstraint(['offence_id'], ['offence.offence_id'], ),
    sa.PrimaryKeyConstraint('offender_id')
    )
    op.create_table('small_scale_farmer',
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('date_of_birth', sa.DateTime(), nullable=False),
    sa.Column('email_address', sa.String(length=225), nullable=False),
    sa.Column('phone_no', sa.String(length=64), nullable=False),
    sa.Column('residential_address', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['member.member_id'], ),
    sa.PrimaryKeyConstraint('farmer_id')
    )
    op.create_index(op.f('ix_small_scale_farmer_farmer_id'), 'small_scale_farmer', ['farmer_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('email_address', sa.String(length=128), nullable=True),
    sa.Column('phone_no', sa.String(length=32), nullable=True),
    sa.Column('residential_address', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email_address'),
    sa.UniqueConstraint('phone_no')
    )
    op.create_table('vehicle',
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('plate_no', sa.String(length=32), nullable=False),
    sa.Column('registration_date', sa.DateTime(), nullable=True),
    sa.Column('make_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['make_id'], ['vehicle_make.make_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('plate_no')
    )
    op.create_table('service',
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('service_id')
    )
    op.create_table('trip',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['driver.driver_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.vehicle_id'], ),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('loader_assignment',
    sa.Column('loader_assignment_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('loader_id', sa.Integer(), nullable=True),
    sa.Column('date_assigned', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loader_id'], ['loader.loader_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.trip_id'], ),
    sa.PrimaryKeyConstraint('loader_assignment_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=True),
    sa.Column('retail_name', sa.String(length=128), nullable=False),
    sa.Column('retail_location', sa.String(length=64), nullable=False),
    sa.Column('retail_email', sa.String(length=128), nullable=False),
    sa.Column('retail_phone_no', sa.String(length=32), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.member_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.trip_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('good_assignment',
    sa.Column('good_assignment_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('good_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['good_id'], ['good.good_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.order_id'], ),
    sa.PrimaryKeyConstraint('good_assignment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('good_assignment')
    op.drop_table('order')
    op.drop_table('loader_assignment')
    op.drop_table('trip')
    op.drop_table('service')
    op.drop_table('vehicle')
    op.drop_table('user')
    op.drop_index(op.f('ix_small_scale_farmer_farmer_id'), table_name='small_scale_farmer')
    op.drop_table('small_scale_farmer')
    op.drop_table('offender')
    op.drop_index(op.f('ix_vehicle_make_make_type'), table_name='vehicle_make')
    op.drop_table('vehicle_make')
    op.drop_table('role')
    op.drop_table('offence')
    op.drop_table('member')
    op.drop_index(op.f('ix_loader_loader_id'), table_name='loader')
    op.drop_table('loader')
    op.drop_table('good')
    op.drop_index(op.f('ix_driver_driver_id'), table_name='driver')
    op.drop_table('driver')
    # ### end Alembic commands ###
